### PR TITLE
Fix bug of geoDistance when we receive a MAX_ULONG

### PR DESCRIPTION
**Pull request by spinach**
Handle the case of receiving a very long value from the engine: 18446744073709551615.

### CODE REVIEW

**Comment by q-litzler** [comment]
Does that mean that the engine sometimes sends bigger value that even a `Long` can hold ?

If not, why not just replacing the `Int` type by a `Long` ?

**Comment by spinach** [comment]
@q-litzler `Long` can hold from -2^63 to 2^63. The MAX_ULong number is 2^64, and unfortunately ULong is not yet supported in the serialization lib https://github.com/Kotlin/kotlinx.serialization/issues/310. This is a temporary fix until the engine stop returning this huge number 😄

**Comment by q-litzler** [comment]
I see ! Excellent research.

**Comment by spinach** [comment]
@q-litzler  Also interesting is this SO thread about that number special number ^^ https://stackoverflow.com/questions/40608111/why-is-18446744073709551615-1-true.

**Comment by spinach** [comment]
@q-litzler We thought about moving to `Long` anyways, but in theory, if we talk about distance in meters, `Int` is more than enough to cover the whole earth. Also it's for consistency with the other fields: if we change that one to `Long`, we should also change other ones that could be concerned. Finally, it breaks compatibility in Kotlin 
image

**Comment by q-litzler** [comment]
Makes sense 👌I approve this pull request ! 🎉

**Pull request merged**
