### PR TITLE
chore/linter: add kotlin linter

### PR DESCRIPTION
**Pull request by Aallam**
- [x] Add kotlin linter
- [x] Automatize lint rules checking and applying

### CODE REVIEW

**Comment by PLNech** [comment]
On a side note, it might be time to remove me ad Quentin from CODEOWNERS and put both of you instead :upside_down_face:

**Comment by Aallam** [comment]
> Removing `public` from all interfaces, exceptions, extension functions, classes like `ClientAnalytics`: can you explain the rationale behind this change? 🤔

Remove redundancy: In Kotlin, if there is no explicit modifier, the default visibility is public 😎   
_(btw, kotlin official libs follow this rule too: kotlin stdlib, ktor, dokka..)_

**Comment by q-litzler** [comment]
> > Removing `public` from all interfaces, exceptions, extension functions, classes like `ClientAnalytics`: can you explain the rationale behind this change? 🤔
> 
> Remove redundancy: In Kotlin, if there is no explicit modifier, the default visibility is public 😎
> _(btw, kotlin official libs follow this rule too: kotlin stdlib, ktor, dokka..)_

https://kotlinlang.org/docs/reference/coding-conventions.html#coding-conventions-for-libraries

**Comment by Aallam** [comment]
> https://kotlinlang.org/docs/reference/coding-conventions.html#coding-conventions-for-libraries

Thank you for the link dropping.
Although this modifier explicit specification rule doesn't seem to be always respected even by Kotlin authors, it still seems redundant to me. 
In the end, code styles are always opinionated, but the important thing, in my opinion, is to "write" or specify those rules and even better by automatizing checking/applying them.

**Comment by q-litzler** [comment]
> In the end, code styles are always opinionated

Indeed. But these rules are not merely stylistic, they also help avoid breaking API compatibility by modifying a return type, or a visibility modifier by accident.

> even better by automatizing checking/applying them.

Agreed 👌

Anyway, it's nice to see there's a new Kotlin boss in town !
Hope you'll have fun with the projects. I'll pop my head sometimes to give some history on some design choices (and mistakes) I made.

**Comment by Aallam** [comment]
> Indeed. But these rules are not merely stylistic, they also help avoid breaking API compatibility by modifying a return type, or a visibility modifier by accident.

Yes, of course! I was just wondering why even JetBrains (and a lot of popular Kotlin libraries) didn't always respect this specific rule! But why not, let's do correctly what they "failed" to do 😎

> Anyway, it's nice to see there's a new Kotlin boss in town !
> Hope you'll have fun with the projects. I'll pop my head in sometimes to give some history on some design choices (and mistakes) I made.

Thank you! please don't hesitate, any feedback is very welcome! 🤗

**Comment by q-litzler** [comment]
> Yes, of course! I was just wondering why even JetBrains (and a lot of popular Kotlin libraries) didn't always respect this specific rule! But why not, let's do correctly what they "failed" to do

I think they don't care as much because they have (or these is) a plugin checking binary compatibility for them

https://github.com/ktorio/ktor/blob/44e9333ff9693b55963a6feef7d408fc91bb3aa5/gradle/compatibility.gradle#L1

**Comment by Aallam** [comment]
> I think they don't care as much because they have (or these is) a plugin checking binary compatibility for them
> 
> https://github.com/ktorio/ktor/blob/44e9333ff9693b55963a6feef7d408fc91bb3aa5/gradle/compatibility.gradle#L1

This is definitely something we can do too!

**Pull request merged**
