### PR TITLE
getSecuredApiKeyRemainingValidity

### LINKED ISSUE #104: New method: GetSecuredApiKeyRemainingValidity
## Summary

When a secured API keys expire, search breaks. The current workaround is more complex
than it needs to be. 

The options for developers using Algolia require, at every place where a search
operation is performed, catching an operation error, identify it as a
"ValidUntil" error, then regenerate the API key, and perform the search
operation again.

The idea is to define a method which tells if a `SecuredAPIKey`
is expired or not without making a single call to Algolia's API.

## References

- Specs: https://github.com/algolia/algoliasearch-client-specs-internal/pull/25

### PR DESCRIPTION
**Pull request by q-litzler**
fix #104

### CODE REVIEW

**Comment by aseure** [comment]
LGTM but I'd rather have @Ant-hem double checking this one.

**Comment by q-litzler** [comment]
Sure. @Ant-hem I looked at your java code to implement this, so it should be straightforward :)

**Comment by Ant-hem** [comment]
LGTM 👍  but I have two questions:

- I saw we are returning `long` don't we want to return a `Duration` object? Or is this irrelevant in the kotlin world? 
- nit: Why is the CI failing for very PR (I can't have access to the details of it :()

**Comment by q-litzler** [comment]
> LGTM 👍 but I have two questions:
> 
> * I saw we are returning `long` don't we want to return a `Duration` object? Or is this irrelevant in the kotlin world?
> * nit: Why is the CI failing for very PR (I can't have access to the details of it :()

Duration object just got released in the new 1.3.50 version of Kotlin. I might have a look :)
I'll fix the CI in other commits.

**Pull request merged**
